### ISSUE TITLE
GD-132: Test parsing is extremely fragile

### ISSUE THREAD

**Issue by zorbathut** [MikeSchulze/gdUnit4Net#132]
### The used GdUnit4 version

4.3.2 (Latest Release)

### The used Godot version

v4.2.2 (custom)

### Operating System

Manjaro Linux

### Describe the bug

The test parsing system is doing a bunch of low-level parsing to discover tests, which ends up meaning that your actual syntax is fragile and prevents tests from being found. This also means that the source code is required to run tests.

### Steps to Reproduce

Here's a test that works:

```cs
using GdUnit4;
using static GdUnit4.Assertions;

[TestSuite]
public class ExampleTest
{
    [TestCase]
    public void Success()
    {
        AssertBool(true).IsTrue();
    }
}
```

Here's a test that doesn't work:

```cs
[GdUnit4.TestSuite]
public class ExampleTest
{
    [GdUnit4.TestCase]
    public void Success()
    {
        AssertBool(true).IsTrue();
    }
}
```

Here's another test that doesn't work:

```cs
using GdUnit4;
using static GdUnit4.Assertions;

public static class Wrapper
{
    [TestSuite]
    public class ExampleTest
    {
        [TestCase]
        public void Success()
        {
            AssertBool(true).IsTrue();
        }
    }
}
```

Here's another test that doesn't work:

```cs
using GdUnit4;
using static GdUnit4.Assertions;

public class TestSuiteTaggedAttribute : TestSuiteAttribute
{
    public TestSuiteTaggedAttribute(string moreData)
    {
    }
}

[TestSuiteTagged("Added by Bob")]
public class ExampleTest
{
    [TestCase]
    public void Success()
    {
        AssertBool(true).IsTrue();
    }
}
```

**Comment by MikeSchulze** [comment]
> Here's a test that doesn't work:
```cs
 [GdUnit4.TestSuite]
public class ExampleTest
{
    [GdUnit4.TestCase]
    public void Success()
    {
        AssertBool(true).IsTrue();
    }
}
```

Thats not a bug.
I have never seen an example using the namespace with testattribute, it is common to write `[TestCase]` only



> Here's another test that doesn't work:
```cs
using GdUnit4;
using static GdUnit4.Assertions;

public static class Wrapper
{
    [TestSuite]
    public class ExampleTest
    {
        [TestCase]
        public void Success()
        {
            AssertBool(true).IsTrue();
        }
    }
}
```

This is not a bug, GdUnit4 do not support nested test classes.
There is no reason to do this actually, you can simply group your tests by using folder structures.


> Here's another test that doesn't work:
```cs
using GdUnit4;
using static GdUnit4.Assertions;

public class TestSuiteTaggedAttribute : TestSuiteAttribute
{
    public TestSuiteTaggedAttribute(string moreData)
    {
    }
}

[TestSuiteTagged("Added by Bob")]
public class ExampleTest
{
    [TestCase]
    public void Success()
    {
        AssertBool(true).IsTrue();
    }
}
```
That's not a bug. GdUnit4 do not support custom test attributes. 

Please read the documentation carefully before open bugs.
Please note that GdUnit4 is only a small unit testing framework and cannot be compared with the scope of NUnit or XUnit.
Since this is a small project and the user base is quite small, I keep the effort and scope of the API as low as necessary. 
All the cases described are not bugs or blockers and can be solved with available means.

You are of course free to create feature requests, it is not useful to simply declare missing functionality as an error. 

Best regards
Mike
